name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Create timestamp variable
      run: |
        echo "timestamp=$(date +%s)" >> $GITHUB_ENV
    
    - name: Get commit SHA
      run: echo "sha=${GITHUB_SHA}" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag nishizhen/opus-mt:${{ env.timestamp }}-${{ env.sha }}
        docker tag nishizhen/opus-mt:${{ env.timestamp }}-${{ env.sha }} nishizhen/opus-mt:latest
    
    - name: Push the Docker image
      run: |
        docker push nishizhen/opus-mt:${{ env.timestamp }}-${{ env.sha }}
        docker push nishizhen/opus-mt:latest
